baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Sylvain Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
 # main:
  #  - identifier: blog
  #    name: Blog
  #    title: Blog posts
  #    url: /blogs
 #     weight: 1
 #   - identifier: gallery
 #     name: Gallery
 #     title: Blog posts
 #     url: /gallery
 #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Sylvain"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/sylvain.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Sylvain Estebe" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: true
      disableExperience: false
      disableEducation: true
      disableProjects: false
      disableProjectsT: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Sylvain."
    subtitle: "I study Cognitive Science"
    content: "I have a background in cognitive science, computer science and mathematics. I have a strong interest in the intersection of technology, art and cognitive behaviour. I also enjoy programming, composing music and photography."



    image: /images/sylvain.png
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1keV3BCRjq9sMVSAuAouwDA-pjynJFX37/view?usp=share_link"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Sylvain119
        - icon: fab fa-twitter
          url: https://twitter.com/sylvain_es
        - icon: fab fa-instagram
          url: https://www.instagram.com/pepside/
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sylvain-estebe-97485a118/

  # About
 # about:
  #  enable: true
  #  title: "About Me"
  #  image: "/images/sylvain.png"
  #  content: |-
  #   I have a background in cognitive science, computer science and #mathematics. I have a strong interest in the intersection of technology, art and cognitive behaviour.
     
  #      Here are some of the programming languages I've recently been studying and using :
 #   skills:
  #    enable: true
 #     title: ""
  #    items:
  #      - "HTML & CSS"
  #      - "C"
  #      - "JavaScript"
  #      - "Java"
   #     - "R"
   #     - "Python"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Research Internship"
        company: "Internship - RITMO"
        companyUrl: "https://www.uio.no/ritmo/english/"
        date: "May 2022 - July 2022"
        
        content: |
         Collection of eye-tracking data to measure and predict emotions induced by music listening.
          - Conduct a literature review
          - Set up a protocol
          - Manipulate the eye tracking technology
          - Recruit participants
          - Manage a passation protocol
          - Collect pupillometry data

      - job: "Composer"
        company: "Independent composer"
        date: "Sep 2015 - Dec 2022"
    
        info:
          enable: true

        content: |
         I have worked with many different artists and musical styles on the composition and production of rythmes and song,

          Composing & Producing pop songs and advertising :
          - Logic Pro X
          - FL Studio
          - Spitfire Audio
          - Midi Keyboard
          
  # Music projects
  projects:
    enable: true
    title: "Projects"
    items:
      - title: Poid Lourd - Disiz
        content: Composer of original sound creation - first version.
        image: /images/projects/poidlourd.png
        featured:
          name: Youtube
          link: https://www.youtube.com/watch?v=snSiqRZDXMI
        badges:
          - "Work collaboration with Hip-hop artist"
          - "FL Studio with plugging"
          - "Midi keyboard"
          - "2022"

      - title: Single Enfants irradiés - Disiz
        content: Integral composer & programming. Does not include - Mixer, Mastering Engineer & Recording Engineer.
        image: /images/projects/enfantirra.jpg
        featured:
          name: Youtube
          link: https://www.youtube.com/watch?v=fu6JhsYiqac
        badges:
          - "Work collaboration with Hip-hop artist"
          - "FL Studio with plugin"
          - "Midi keyboard"
          - "2019"

      - title: Albums - Jok'air 
        content: Single composer for the albums Big Daddy Jok, Je suis Big Daddy & Jok'Rambo (22 tracks).
        image: /images/projects/squale.jpg
        featured:
          name: Tidal
          link: https://tidal.com/browse/credits/8569123
        badges:
          - "Integral composer"
          - "Work collaboration with Rap artist"
          - "FL Studio with plugin"
          - "Midi keyboard"
          - "Collaboration with professional musicians for sound recording"
          - "2017"

      - title: Song Composer - Courir & Adidas publicity 
        content: Original composition for a publicity, created rhythms and melodies. Addition of samples.
        image: /images/projects/courxadi.png
        featured:
          name: Video
          link: https://www.facebook.com/pepsidebeats/videos/553104515263771
        badges:
          - "Composer"
          - "Picture and sound in harmony"
          - "FL Studio with plugin"
          - "2019"

      - title: One Man Show - Panayotis Pascot
        content: Independent composer for one man show at Theatre Antoine in Paris. Original sound creation.
        image: /images/projects/pana.png
        featured:
          name: Youtube
          link: https://www.youtube.com/watch?v=1lqLuY4d86k
        badges:
          - "Composer"
          - "Work collaboration"
          - "FL Studio with plugin"
          - "2020"
          
  # Technology projects
  projectsT:
    enable: true
    title: "Technology projects"
    items:
      - title: 2048 video game in 3D
        content: Programming team work project. My personal work consisted of creating the graphical interface, creating and implementing a database, and implementing the Alphabeta artificial intelligence algorithm. Introduced Scrum and Agile project management methods using SQL, Always Data, PhpMyAdmin, Java Fx and Github.
          
        image: /images/projects/2048_3d.jpg
        featured:
          name: Github
          link: https://github.com/Sylvain119/Projet2048_Berdoll_Estebe_Worm_Jegham.git

  # Achievements
  achievements:
    enable: true
    title: "Interest"
    items:
      - title: "Mooc - Pupillometry,The Eye as a Window into the Mind - Achievements"
        content: Examine the science of pupillometry and explore the eye as a window into the mind with the University of Oslo.
        url: "https://www.futurelearn.com/certificates/k5jbltj"
            
            
      - title: "Mooc - Motion Capture: The Art of Studying Human Activity - Week 3/6"
        content: Learn about how to record, visualize, and analyze human body motion - University of Oslo
        url: https://www.futurelearn.com/courses/motion-capture-course
        
      - title: "Mooc - Introduction to Programming with Python - Week 3/4"
        content: Build your programming skills and learn the basics of the Python programming language, from logic and functions to debugging.
        url: "https://www.futurelearn.com/courses/introduction-to-programming-with-python-fourth-rev-e"
          
  #Contact
  contact:
    enable: true
    title: "Contact"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: sylvain.estebe@gmail.com
    btnName: Mail me
